'use client';

import React, { useState } from 'react';

type StepType = 'email' | 'linkedin' | 'call' | 'wait';

interface SequenceStep {
  id: string;
  type: StepType;
  title: string;
  details: string;
}

export default function PlaybookBuilder() {
  const [steps, setSteps] = useState<SequenceStep[]>([
    { id: '1', type: 'email', title: 'Automated Email: Intro', details: 'Generated by Personalization Agent' },
    { id: '2', type: 'wait', title: 'Wait', details: '2 Days' },
    { id: '3', type: 'linkedin', title: 'LinkedIn Connect', details: 'With personalized note' }
  ]);

  const addStep = (type: StepType) => {
    let title = '';
    let details = '';
    if (type === 'email') { title = 'Automated Email'; details = 'Drafted by AI'; }
    if (type === 'linkedin') { title = 'LinkedIn Task'; details = 'Action required'; }
    if (type === 'call') { title = 'Phone Call'; details = 'Script by Strategy Agent'; }
    if (type === 'wait') { title = 'Wait'; details = '1 Day'; }

    setSteps([...steps, { id: Date.now().toString(), type, title, details }]);
  };

  const removeStep = (id: string) => {
    setSteps(steps.filter(s => s.id !== id));
  };

  return (
    <div className="flex h-screen w-full overflow-hidden text-slate-200">
      
      {/* Sidebar Navigation (Reused design style) */}
      <aside className="w-64 border-r border-white/5 bg-slate-900/50 backdrop-blur-xl flex flex-col h-full shrink-0 hidden md:flex sticky top-0">
        <div className="p-6 border-b border-white/5 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-teal-400 flex items-center justify-center shadow-lg shadow-blue-500/20">
             <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/></svg>
          </div>
          <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
            SalesOps<span className="text-blue-400">AI</span>
          </h1>
        </div>
        <nav className="flex-1 px-4 space-y-2 mt-4">
          <NavItem href="/" icon="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">Dashboard</NavItem>
          <NavItem href="/playbooks/new" active icon="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2">Playbook Builder</NavItem>
          <NavItem href="/cadences" icon="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6">Live Cadences</NavItem>
          <NavItem href="/leads" icon="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z">Lead Canvas</NavItem>
          <NavItem href="/settings" icon="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z">Settings</NavItem>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto p-6 md:p-10 flex flex-col h-full">
        <header className="flex justify-between items-center mb-10 shrink-0">
          <div>
            <div className="text-sm text-teal-400 font-medium mb-1">Strategy Agent</div>
            <h2 className="text-3xl font-bold tracking-tight mb-1 hidden md:block">Playbook Builder</h2>
            <p className="text-slate-400">Design automated sequences powered by AI personalization.</p>
          </div>
          <div className="flex gap-3">
             <button onClick={() => alert('Draft saved successfully.')} className="px-5 py-2.5 rounded-lg border border-white/10 hover:bg-white/5 transition-colors text-sm font-medium">Save Draft</button>
             <button onClick={() => alert('Playbook Activated! Sending sequences to Event Bus.')} className="glass-card hover-glow px-5 py-2.5 flex items-center gap-2 text-sm font-medium text-white shadow-[0_0_20px_rgba(20,184,166,0.2)]">
               Activate Playbook
             </button>
          </div>
        </header>

        <div className="flex-1 flex gap-8 min-h-0">
          
          {/* Canvas Area */}
          <div className="flex-1 glass-card p-8 overflow-y-auto rounded-2xl relative">
            <h3 className="text-xl font-semibold mb-8">Sequence Flow</h3>
            
            <div className="max-w-xl mx-auto space-y-4">
              {steps.map((step, index) => (
                <div key={step.id} className="relative">
                  {/* Connection Line */}
                  {index !== 0 && (
                     <div className="absolute -top-4 left-6 w-0.5 h-4 bg-white/10"></div>
                  )}
                  
                  <div className="bg-black/40 border border-white/10 rounded-xl p-4 flex items-center gap-5 hover:border-white/20 transition-colors group">
                     {/* Step Icon */}
                     <div className={`w-12 h-12 rounded-lg flex items-center justify-center shrink-0 ${
                       step.type === 'email' ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30' :
                       step.type === 'linkedin' ? 'bg-sky-500/20 text-sky-400 border border-sky-500/30' :
                       step.type === 'call' ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' :
                       'bg-slate-700/50 text-slate-300 border border-white/5'
                     }`}>
                       {step.type === 'email' && <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>}
                       {step.type === 'linkedin' && <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>}
                       {step.type === 'call' && <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg>}
                       {step.type === 'wait' && <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
                     </div>
                     
                     <div className="flex-1">
                       <h4 className="font-medium text-white text-lg">{step.title}</h4>
                       <p className="text-sm text-slate-400">{step.details}</p>
                     </div>
                     
                     <button onClick={() => removeStep(step.id)} className="opacity-0 group-hover:opacity-100 p-2 text-slate-400 hover:text-red-400 transition-all">
                       <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" /></svg>
                     </button>
                  </div>
                </div>
              ))}
              
              <div className="pt-4 flex justify-center">
                 <div className="w-0.5 h-8 bg-white/10 mb-4"></div>
              </div>
              
              <div className="flex flex-wrap justify-center gap-3">
                 <button onClick={() => addStep('email')} className="flex items-center gap-2 px-4 py-2 bg-blue-500/10 hover:bg-blue-500/20 text-blue-400 rounded-full border border-blue-500/20 transition-colors text-sm font-medium">
                   + Add Email
                 </button>
                 <button onClick={() => addStep('linkedin')} className="flex items-center gap-2 px-4 py-2 bg-sky-500/10 hover:bg-sky-500/20 text-sky-400 rounded-full border border-sky-500/20 transition-colors text-sm font-medium">
                   + Add LinkedIn
                 </button>
                 <button onClick={() => addStep('call')} className="flex items-center gap-2 px-4 py-2 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 rounded-full border border-emerald-500/20 transition-colors text-sm font-medium">
                   + Add Call
                 </button>
                 <button onClick={() => addStep('wait')} className="flex items-center gap-2 px-4 py-2 bg-slate-700/30 hover:bg-slate-700/50 text-slate-300 rounded-full border border-white/10 transition-colors text-sm font-medium">
                   + Add Wait
                 </button>
              </div>
            </div>

          </div>

          {/* Settings / Configuration Panel */}
          <div className="w-80 shrink-0 bg-black/40 border-l border-white/5 rounded-2xl p-6 flex flex-col gap-6 overflow-y-auto hidden lg:flex">
             <div>
               <h3 className="text-lg font-semibold mb-1">Playbook Settings</h3>
               <p className="text-sm text-slate-400">Configure global rules.</p>
             </div>
             
             <div className="space-y-4">
               <div>
                 <label className="block text-sm font-medium mb-1">Playbook Name</label>
                 <input type="text" defaultValue="Enterprise Outbound Q3" className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500 transition-colors" />
               </div>
               
               <div>
                 <label className="block text-sm font-medium mb-1">Target Audience</label>
                 <select className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-500 transition-colors appearance-none">
                   <option>VP of Sales / RevOps</option>
                   <option>CTO / VPEng</option>
                   <option>Marketing Directors</option>
                 </select>
               </div>
               
               <div className="pt-4 border-t border-white/10">
                 <h4 className="text-sm font-medium mb-3 flex items-center gap-2">
                   <svg className="w-4 h-4 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                   AI Personalization Focus
                 </h4>
                 
                 <div className="space-y-2">
                   <label className="flex items-center gap-3 text-sm">
                     <input type="checkbox" defaultChecked className="w-4 h-4 bg-black/50 border-white/20 rounded text-blue-500 focus:ring-blue-500" />
                     Reference recent company news
                   </label>
                   <label className="flex items-center gap-3 text-sm">
                     <input type="checkbox" defaultChecked className="w-4 h-4 bg-black/50 border-white/20 rounded text-blue-500 focus:ring-blue-500" />
                     Mention shared connections
                   </label>
                   <label className="flex items-center gap-3 text-sm">
                     <input type="checkbox" className="w-4 h-4 bg-black/50 border-white/20 rounded text-blue-500 focus:ring-blue-500" />
                     Optimize for short mobile reading
                   </label>
                 </div>
               </div>
               
             </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function NavItem({ active, icon, href, children }: { active?: boolean, icon: string, href: string, children: React.ReactNode }) {
  return (
    <a href={href} className={`flex items-center gap-3 px-3 py-2.5 rounded-lg transition-all duration-200 ${active ? 'bg-white/10 text-white font-medium shadow-[0_0_15px_rgba(255,255,255,0.05)]' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}>
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={icon} /></svg>
      {children}
    </a>
  );
}
